development:
  adapter: postgresql
  encoding: utf8
  database: periodic_calculations_development
  pool: 5
  host: 127.0.0.1
  username: rewardli_su
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: periodic_calculations_test
  pool: 5
  host: 127.0.0.1
  username: postgres
  password:
  timeout: 5000

